python train.py --model logistic --topk 12 --lr 0.0001
python train.py --model logistic --topk 12 --lr 0.001
python train.py --model logistic --topk 12 --lr 0.005
python train.py --model logistic --topk 12 --lr 0.01
python train.py --model logistic --topk 9 --lr 0.0001
python train.py --model logistic --topk 9 --lr 0.001
python train.py --model logistic --topk 9 --lr 0.005
python train.py --model logistic --topk 9 --lr 0.01
python train.py --model logistic --topk 6 --lr 0.0001
python train.py --model logistic --topk 6 --lr 0.001
python train.py --model logistic --topk 6 --lr 0.005
python train.py --model logistic --topk 6 --lr 0.01
python train.py --model logistic --topk 3 --lr 0.0001
python train.py --model logistic --topk 3 --lr 0.001
python train.py --model logistic --topk 3 --lr 0.005
python train.py --model logistic --topk 3 --lr 0.01
python train.py --model logistic --topk 1 --lr 0.0001
python train.py --model logistic --topk 1 --lr 0.001
python train.py --model logistic --topk 1 --lr 0.005
python train.py --model logistic --topk 1 --lr 0.01